name: star_resonance_library
description: "Star Resonance Game Library."

publish_to: 'none'

version: 0.0.4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  # 基础
  event_bus: ^2.0.1

  # 图像识别相关
  opencv_core: ^1.4.3
  image: ^4.5.4

  # windows api相关
  win32: ^5.14.0

  # ui相关
  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  getwidget: ^6.0.0
  animations: ^2.0.11
  flutter_svg: ^2.2.0
  go_router: ^16.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  build_runner: ^2.5.2
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/icon/
    - assets/data/
  fonts:
    - family: ResourceHanRoundedCN
      fonts:
        - asset: assets/fonts/ResourceHanRoundedCN-Regular.ttf
          weight: 300
        - asset: assets/fonts/ResourceHanRoundedCN-Bold.ttf
          weight: 700
        - asset: assets/fonts/ResourceHanRoundedCN-Medium.ttf
          weight: 500
        - asset: assets/fonts/ResourceHanRoundedCN-Normal.ttf
          weight: 400
    - family: ResourceHanRoundedJP
      fonts:
        - asset: assets/fonts/ResourceHanRoundedJP-Regular.ttf
          weight: 300
        - asset: assets/fonts/ResourceHanRoundedJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/ResourceHanRoundedJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/ResourceHanRoundedJP-Normal.ttf
          weight: 400
hooks:
  user_defines:
    dartcv4:
      exclude_modules:
        - contrib
        - dnn
        - features2d
        - core
      include_modules:
        - core
        - imgproc
        - videoio